name:                gcr-haskell-example
version:             0.1.0.0
github:              "rhalldearn/gcr-haskell-example"
license:             MIT
author:              "rhalldearn"
maintainer:          "richard.halldearn@gmail.com"
copyright:           "2019 rhalldearn"

extra-source-files:
  - static/index.html
  - static/ui.js
  - README.md
  # - ChangeLog.md
 

# Metadata used when publishing your package
# synopsis:            cloud function example
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rhalldearn/gcr-haskell-example#readme>

dependencies:
- hspec
- hspec-wai
- base >= 4.7 && < 5
- text
- servant
- servant-server
- transformers
- aeson
- wai
- warp
- servant-js
- random
- js-jquery
- markdown-unlit >= 0.5.0 && <0.6
- servant-auth
- servant-auth-client
- servant-auth-docs
- servant-auth-server
- servant-auth-swagger
- mtl

library:
  default-language:    Haskell2010
  default-extensions: AutoDeriveTypeable ConstraintKinds DataKinds DefaultSignatures DeriveFoldable DeriveFunctor DeriveGeneric DeriveTraversable FlexibleContexts FlexibleInstances FunctionalDependencies GADTs KindSignatures MultiParamTypeClasses OverloadedStrings RankNTypes ScopedTypeVariables TypeFamilies TypeOperators
  ghc-options:         -Wall -pgmL markdown-unlit
  source-dirs: src

executables:
  app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - gcr-haskell-example

tests:
  app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - gcr-haskell-example
      - string-conversions
