apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: gcr-haskell-example
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/{username}/gcr-haskell-example
            env:
              - name: TARGET
                value: "app-exe"
